### ISSUE TITLE
Get brightness on Android

### ISSUE THREAD

**Issue by arstiefel** [Calvin-Huang/react-native-device-brightness#2]
Get brightness on Android returns -1

**Comment by Calvin-Huang** [comment]
Thanks! @stief510 
However I have no Android device now.
But I promise that it'll be fixed ASAP.

**Comment by Calvin-Huang** [comment]
Hi @stief510 
According the [Android document - BRIGHTNESS_OVERRIDE_NONE](https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#screenBrightness).

_Default value `-1` indicating that the brightness value is not overridden for this window and normal brightness policy should be used._

Returning `-1` is correct behavior. But I think it should be documented to README.
I'll add it up and try to figure out a better way to unify iOS and Android's behavior.
