### ISSUE TITLE
Cannot read property 'getBrighnessLevel' of undefined

### ISSUE THREAD

**Issue by BennyTian** [Calvin-Huang/react-native-device-brightness#7]
hi : 
Im installed by READ.ME for RN-Android.  
when i import Modules and got execption  :

`Cannot read property 'getBrighnessLevel' of undefined` 

code:
`import DeviceBrightness from 'react-native-device-brightness';`

react-native version: 0.41.2
react-native-device-brightness : 1.1.1

Thanks.

BTW: IOS is OK.

**Comment by dasoga** [comment]
What was the fix here? I have sam issue but in iOS
